language: go

go:
  - 1.7.x

before_install:
  - go get github.com/mattn/goveralls

install:
  - go get -t -v .

before_script:
  - go vet ./...

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
