language: go

go:
  - 1.7.x

before_install:
  - go get github.com/mattn/goveralls

install:
  - go get -t -v .

before_script:
  - go vet ./...

script:
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
